packages:
  - apps/*
  - packages/*

catalog:
  '@trpc/client': ^11.7.2
  '@trpc/server': ^11.7.2
  '@trpc/tanstack-react-query': ^11.7.2
  better-auth: ^1.4.18
  dotenv: ^17.2.2
  drizzle-orm: ^0.45.1
  next: ^16.1.1
  typescript: ^5
  zod: 'catalog:'
